/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueNameRouteImport } from './routes/catalogue.$name'

const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueNameRoute = CatalogueNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => CatalogueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/catalogue/$name': typeof CatalogueNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/catalogue/$name': typeof CatalogueNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/catalogue/$name': typeof CatalogueNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogue' | '/catalogue/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogue' | '/catalogue/$name'
  id: '__root__' | '/' | '/catalogue' | '/catalogue/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$name': {
      id: '/catalogue/$name'
      path: '/$name'
      fullPath: '/catalogue/$name'
      preLoaderRoute: typeof CatalogueNameRouteImport
      parentRoute: typeof CatalogueRoute
    }
  }
}

interface CatalogueRouteChildren {
  CatalogueNameRoute: typeof CatalogueNameRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueNameRoute: CatalogueNameRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
